Repository kasvith/kache, pull requests merged in 2018-08, with the labels that each got.

#1 Makefile Updated
  .travis.yml
  makefile
Labels: enhancement

#2 Types/list
  .travis.yml
  README.md
  cmd/kache/.gitignore
  cmd/kache/main.go
  internal/.Keep
  internal/config/options.go
  internal/kache/app.go
  internal/snapshot/snapshot.go
  internal/types/list/list.go
  internal/types/list/list_test.go
  pkg/testsuite/assert.go
Labels: enhancement

#5 Added HashMaps to types
  .travis.yml
  cmd/kache/.gitignore
  internal/types/hashmap/hmap.go
  internal/types/hashmap/hmap_test.go
  makefile
  pkg/testsuite/assert.go
Labels: feature

#7 Added Set to Types
  .travis.yml
  internal/types/set/set.go
  internal/types/set/set_test.go
Labels: feature

#8 Updated to have a pointer of mux
  internal/types/hashmap/hmap.go
  internal/types/list/list.go
Labels: bug

#15 added logger types
  config/kache.default.toml
  internal/cobra-cmds/kache/root.go
  internal/config/app.go
  internal/klogs/loggers.go
Labels: accepted, enhancement, feature, level:beginner, pr proposed, server

#19 switched to RWMutex to avoid fully locking if only reads occur
  pkg/types/hashmap/hmap.go
  pkg/types/list/list.go
  pkg/types/set/set.go
Labels: accepted, enhancement, good first issue, level:intermediate, pr proposed, server

#25 fixed wrong calculation of intersection
  pkg/types/set/set.go
Labels: accepted, bug, level:intermediate, pr proposed, server

#32 split standard and third-party packages imports(fix #30)
  .travis.yml
  cmd/check_fmt.sh
  cmd/check_imports.sh
  cmd/kache-doc-gen/main.go
  internal/cmds/strings.go
  internal/cobra-cmds/kache/root.go
  internal/cobra-cmds/kache/version.go
  internal/klogs/loggers.go
  internal/protcl/parser.go
  internal/protcl/resp_test.go
  internal/srv/clients.go
  internal/srv/tcp.go
  makefile
  pkg/types/hashmap/hmap_test.go
  pkg/types/list/list.go
  pkg/types/list/list_test.go
  pkg/util/strs_test.go
Labels: Code Style, accepted, enhancement, staging

#34 removed the extra writer
  internal/srv/tcp.go
Labels: bug, level:beginner, server

#35 Fix/init readers
  internal/srv/tcp.go
Labels: bug, level:beginner, server

#41 move to dep
  .travis.yml
  cmd/check_fmt.sh
  cmd/check_imports.sh
  makefile
Labels: accepted, enhancement, pr proposed, server, staging

#42 add unified args number check
  internal/arch/command-table.go
  internal/arch/command-table_test.go
  internal/cmds/keys.go
  internal/cmds/server.go
  internal/cmds/strings.go
Labels: WIP, accepted, enhancement, level:intermediate, pr proposed, server

#53 fix boolean check
  internal/klogs/loggers.go
  internal/protcl/resp.go
  pkg/types/list/list.go
Labels: Code Style, accepted, level:beginner, server

#52 fix unbalanced quotes string
  pkg/util/strs.go
  pkg/util/strs_test.go
Labels: bug, level:intermediate, server

#60 Feature/mage is here
  .travis.yml
  Gopkg.lock
  README.md
  appveyor.yml
  internal/cobra-cmds/kache/version.go
  magefile.go
Labels: WIP, enhancement, level:intermediate, server

#65 Enhancement/clients
  .gitignore
  internal/srv/client.go
  internal/srv/clients.go
  internal/srv/tcp.go
  magefile.go
Labels: Code Style, enhancement, level:intermediate, server

#68 fix/recoverable errors
  internal/cobra-cmds/cli/root.go
  internal/cobra-cmds/cli/version.go
  internal/cobra-cmds/kache/root.go
  internal/cobra-cmds/version.go
  internal/protcl/errors.go
  internal/protcl/parser.go
  internal/srv/client.go
Labels: WIP, bug, level:intermediate, server

#70 fix/client-flags
  internal/cli/cli.go
  internal/cobra-cmds/cli/root.go
Labels: WIP, accepted, bug, cli, level:beginner

#71 enhancement/added keys to commands
  internal/arch/command-table.go
  internal/cli/conn.go
  internal/cmds/keys.go
  internal/db/db.go
Labels: enhancement, level:beginner, server

#73 Fix/typo in sets
  pkg/types/set/set.go
Labels: bug

#74 Fix/thou shalt not defer
  pkg/types/hashmap/hmap.go
  pkg/types/list/list.go
  pkg/types/set/set.go
Labels: Code Style, bug, server

#75 Fix/thou shalt not make
  cmd/check_fmt.sh
  cmd/check_imports.sh
  makefile
Labels: Code Style, enhancement

#83 add resp3 protocol part 5(replace to resp3)
  internal/arch/command-table.go
  internal/arch/command-table_test.go
  internal/cli/cli.go
  internal/cli/cli_test.go
  internal/cli/conn.go
  internal/cmds/keys.go
  internal/cmds/server.go
  internal/cmds/strings.go
  internal/db/db.go
  internal/protcl/resp3.go
  internal/protcl/resp3_parser.go
  internal/srv/client.go
Labels: Code Style, WIP, enhancement, level:intermediate, server
